### ISSUE TITLE
Custody fees on gold chain

### ISSUE THREAD

**Issue by gmachtel** [nbh-digital/goldchain#24] opened 2019-07-15 14:50 UTC
Daily fee of 0.0025% to be withdrawn from GFTs as 'unspendable'. Only spendable GFTs can be used for transactions. Calculated unspendable GFTs calculated, based on timeframe between last transaction and current transaction to be transferred to NBH (the gold company) wallet at earliest signed transaction (transfer, burn, atomic swap).

**Comment by robvanmieghem** [comment] 2019-07-19 07:20
@despiegk This seems a requirement now even though I thought this was not, it also has a direct impact on the eurotoken:  https://github.com/nbh-digital/eurochain/issues/2

**Comment by GlenDC** [comment] 2019-07-29 14:13
Technically this feature can be achieved as follows.

Write a goldchain-specific Rivine Extension, that we can provide as a Goldchain module `github.com/nbh-digital/goldchain/pkg/extensions/custodyfee`:
    - this extension will provide a new condition, the "CustodyCondition", which cannot be fulfilled, and contains no data of its own;
   - this extension will provide a plugin:
       - the plugin will store meta information (block ID, block Height, block timestamp, transaction ID) for each coin output. Stored output metadata needs to be updated for each tx that gets reverted<sup>(1)</sup> and applied for both coin inputs and outputs;
       - the custody condition will be auto-registered (and thus supported by Rivine) when creating the plugin;
       - the plugin will provide a global transaction validator (a validator that applies to any transaction, not of a specific version only) that will check for all coin input and outputs as found in the transaction. For each coin input the validator can look up the timestamp of the coin output when it was created, such that it can compute based on the value of that coin output how much custody fee needs to be paid in order to spent it. The validator will than be able to check that the total sum of custody fees to be paid equals the actual paid custody fees (exactly) by summing all the coin outputs that use the "CustodyFeeCondition" in the coin outputs (these custody fee coin outputs can be in any position, and be just one output or multiple outputs, as long as the value sum matches the expected value it is good);
    - Light Clients (Threefold Desktop Wallet, 3Bot Wallet) will need to compute the required custody fees for coin outputs to be spend as coin inputs themselves and define these paid custody fees as one or multiple coin outputs for each transaction they make and post. In order to do so they will need to know the created timestamp of each coin output as well as the current chain timestamp. The current chain timestamp they can already have <sup>(2)</sup>, to get the timestamp for each coin outputs there are two options I see:
       - (1) (Currently transactions returned for an unlockhash by the explorer module (the endpoint used by all rivine-based light clients) does not return the parent's block timestamp (Threefold Desktop Wallet gets around this by doing an extra call for each block ID it uses as to be able to get the timestamp), so either we start returning the entire block (or just specific info from a block, such as timestamp) for each returned ExplorerTransaction as we have that info anyhow (see <https://github.com/threefoldtech/rivine/issues/532>) or we choose for option (2);
       - (2) We provide an explorer `/custodyfee/coins/outputs?id=xxxx&id=yyyyy` endpoint that allows looking up the metadata information for one or multiple coin outputs, in one call. In a way this is stupid though as the clients already get so much information fo each unlockhash explorer call as describe in option (1), so we might as well extend that call and go fo option (1);
   - There are some CLI client-related details that need to be worked out <sup>(3)</sup>;

This way each transaction that spends coin inputs will be ensured that it has matching coin outputs to pay for the custody fees. Note that this does imply that this extension is not compatible with for example the ERC20 or 3Bot code (as the client code provided by that functionality does not take into account the extra coin outputs it needs to define and the less money it can refund as a result). But as the Goldchain does not use that code or is planning to use it, that is no issue at all.

----

- _(1)_: 💡This is currently an issue though. The Transaction Validators currently get only the regular block/transaction that is to be applied. It does get a consensusStateGetter interface which it can use to fetch unspent coin outputs, but that means it cannot really recover reverted coin inputs that were removed for example. Instead we can probably rework the TransactionValidators a bit, such that we can also return the matching coin outputs and blockstake outputs for the spent coin inputs and block stake outputs. This is possible as internally in the consensus we have it as a `processedBlock`, that contains diffs, containing exactly that info. So repacking it as some kind of ConsensusBlock` and `ConsensusTransaction`, adding these matching outputs, will allow the reverting of coin inputs for the custody fee extension-plugin. In fact it might even make the consensusStateGetter obsolete so we can remove that as well, given that the matching outputs for each input will be already as part of the validators tx call;
- _(2)_: ⚠️ 💀 Writing my current knowledge for a technical solution for this feature request, I think about something. I do not think we can really confidently implement this feature this way as-is. Imagine you are a light client and compute the fee for the current timestamp. Just as you did that, a new block gets created and thus a new(er) timestamp is now active that will be used for validating your transaction. In fact even if you managed to post it in the tx pool, it will fail once it is part of an actual block, as that block's timestamp will be by definition newer. Some solutions that come to mind:
   - implement client in such a way that they always pay for 10 blocks ahead or so, this will mean they pay `0.00003472222%` too much (on average, taking into account 2 mins per block on avg), which is small enough I would think. Perhaps 10 blocks is too much or too little. But implementing this buffer zone, and allowing transactions from paying too much custody fee (but still not less obviously) might be an easy fix, paid for by the customer...
    - Include in the condition fee the current timestamp the user has fo the blockchain (this way the "custody fee condition" will have data, a timestamp value), where we do not allow timestamps older than 30 mins or so of the block they'll be part off. The timestamps of the custody fee will be part of the signature data and thus cannot be modified after tx creation, while we can in a reproducible way validate that the custody fee is correct and the same as the user calculated in a fair way. This does mean that an evil user with custom code could potentially shave up to `0.00010416666%` from the to be paid fee, but that is small enough I would say, and it would at least not make the user pay fo this imperfection. On top of that, as most users will use our clients, it won't really be abused either. We could make the allowed timestamp difference (blockTS-givenTS) smaller than 30 minutes as well, but need to ensure it is not too small, as to allow it to be in the pool for a while.
- _(3)_: 💻 ⚠️ Some default behaviour will have to be overridden somehow in order for it to still work for the goldchain CLI client and other _local_ REST clients:
    - sending coins/blockstakes will need to be done using a custom function, as it will have to create the required custody fee outputs and foresee more funding or less refunding. Another approach could be that the wallet can be modified using a plugin to allow for such differences, given this functionality goes via the wallet anyhow, this is less preferable imho though.
    - any other CLI functionality that creates transactions WITH coin inputs will need to be modified for the goldchain (or copied over and used instead of...) to create the required custody fees and fund more (or refund less)

**Comment by GlenDC** [comment] 2019-07-29 15:22
Extra note. When implementing the proposal as given in the last comment you'll also need to update the Minter extension. It should accept multiple coin outputs, for the coin destruction Tx, not just a single (optional refund) coin output. This has to be done before you ever plan to use it fo tfchain, as to not get nasty blockheight-restriction code in there.

**Comment by robvanmieghem** [comment] 2019-09-09 10:42
https://github.com/nbh-digital/goldchain/blob/master/specs/custody.md

**Comment by GlenDC** [comment] 2019-10-01 14:52
Code and progress can be followed on the **WIP** PR+branch @ https://github.com/nbh-digital/goldchain/pull/60.

**Comment by GlenDC** [comment] 2019-10-01 15:05
Validation is done shipped as a goldchain-specific consensus extension plugin.

When trying to send coins now, I get:

```
$ goldchainc wallet send coins 01f68299b26a89efdb4351a61c3a062321d23edbc1399c8499947c1313375609adbbcd3977363c 5000
Could not send coins: HTTP 500 error: error after call to /wallet/coins: tx does not contain the required coin output for the custody fee, while coin inputs are spent
```

Which is exactly as expected. Next step will be to support the custody fees in the HTTP API, command line client and frontend explorer.

**Comment by GlenDC** [comment] 2019-10-02 09:16
On a sidenote...

Not sure if this is intended or not, but having these custody fees might mean that people move their tokens faster to a new owner, instead of sitting on a bunch of tokens for long. Why? Well, tokens you hold on to decrease in value every second you keep them, not by much, but given enough time and you might lose quite a lot in custody fees. Not sure how it will really impact things, but it would surprise me if people hold on to (GFT) tokens for very long.

**Comment by gmachtel** [comment] 2019-10-02 09:30
Idea is to keep, I believe, also transaction fees on the chain. If we don't do that, penalty to do fake transfer and hereby overloading the network is too low. Try fee won't be big either. We should find a balance to give incentive not to transfer GFTs for no reason, but at the same time not to cannibalize the revenue model of NBH. See also https://github.com/threefoldtech/rivine/blob/master/doc/new_chain/transactionfees.md

**Comment by GlenDC** [comment] 2019-10-02 09:33
Sure, I was never trying to imply we were to remove transaction fees at some point, in fact I said the opposite, we definitely do want to keep those in for several reasons. Up to you to lower them if needed.

**Comment by GlenDC** [comment] 2019-10-02 15:30
Progress Tracker:

- Goldchain, Rivine and Friends:
  - [x] plugin (consensus) as custody fees extension
  - [x] design+spec custody fee algo
  - [x] HTTP API Custody Fees
  - [ ] Explorer (frontend+backend) (in progress)
  - [ ] wallet daemon (goldchaind) - custody fee support (in progress)
  - [ ] wallet commands - custody fee support
  - [ ] minting breaking change (support multiple coin outputs, + keep compatibility tfchain))
  - [ ] overwrite minting wallet cmds for custody fee support
- External Light Clients:
  - [ ] JSX support for custody fees in goldchain (development branch)
  - [ ] Desktop Wallet support for custody fees in goldchain (master branch)

**Comment by GlenDC** [comment] 2019-10-02 20:25
Made quite a lot of progress today once again, explorer has most support ready, in frontend and backend for custody fees. Here are already some sneak info previews:

<img width="887" alt="Screenshot 2019-10-02 at 16 38 08" src="https://user-images.githubusercontent.com/3900482/66078865-29f5ac00-e563-11e9-8594-3f8a8ab947d3.png">
> Coin Output information in the Transaction Page,
> will improve more by giving more and better information, and on top of
> that it will also correctly handle spent/unspent coin outputs at all times.
<img width="874" alt="Screenshot 2019-10-02 at 16 42 28" src="https://user-images.githubusercontent.com/3900482/66078866-29f5ac00-e563-11e9-9fe6-ebdb09f98b75.png">
> Coin Output information in the Coin Output Page,
> will improve more by giving more and better information, and on top of
> that it will also correctly handle spent/unspent coin outputs at all times.

Miner Payouts are in frontend and backend supported already as well, but will require a Plugin update in the RIvine system, as to allow plugins to be aware of block headers that get applied and reverted at all times, as currently this is not the case for all paths.

I think we're half way, but it's starting to come together.

**Comment by GlenDC** [comment] 2019-10-03 19:54
Bugs are fixed (In Rivine and Goldchain), explorer is ready (frontend and backend) and rivine is up to date.

Some more preview screenshots:

<img width="599" alt="Screenshot 2019-10-03 at 21 01 58" src="https://user-images.githubusercontent.com/3900482/66159362-1c562a00-e628-11e9-9b64-17639dd8ec24.png">
<img width="595" alt="Screenshot 2019-10-03 at 21 43 26" src="https://user-images.githubusercontent.com/3900482/66159364-1c562a00-e628-11e9-82f3-6c359d81ee0d.png">
<img width="620" alt="Screenshot 2019-10-03 at 21 46 48" src="https://user-images.githubusercontent.com/3900482/66159365-1c562a00-e628-11e9-96c1-41d809728624.png">
<img width="598" alt="Screenshot 2019-10-03 at 21 53 25" src="https://user-images.githubusercontent.com/3900482/66159431-43146080-e628-11e9-818b-38b9e23ab43e.png">

**Comment by GlenDC** [comment] 2019-10-04 10:26
A custody fee explorer module has been added, so we can keep track of some global stats:

<img width="832" alt="Screenshot 2019-10-04 at 12 25 18" src="https://user-images.githubusercontent.com/3900482/66200808-1ef56580-e6a2-11e9-86a8-e8a94b7a81aa.png">

**Comment by GlenDC** [comment] 2019-10-04 14:26
Wallet changes (API/CLI/Daemon) are in progress...

Balance fetching is already using correctly the custody fees plugin to give the spendable amount, instead of the coin output creation amounts:

```
$ goldchainc wallet
Wallet status:
Unencrypted, Unlocked
Confirmed Balance:   98541017.385864249 GFT
Locked Balance:      0 GFT
Custody Fees To Pay: 1464852.614135751 GFT
Unconfirmed Delta:   + 0 GFT
BlockStakes:         3000 BS
```

**Comment by GlenDC** [comment] 2019-10-05 20:34
- add custody fees when funding coins using daemon wallet, this finally allows coins to be transferred again on goldchain;
- improve explorer:
   - support for custody fee void address;
   - fix bugs related to custody fees in frontend and backend;
- do not check auth addresses for nil hash, atomic swap contracts and custody fee address;

**Comment by GlenDC** [comment] 2019-10-05 20:37
Some screenshots on latest explorer frontend as rendered by the codebase inhttps://github.com/nbh-digital/goldchain/pull/60:

<img width="560" alt="Screenshot 2019-10-05 at 22 28 02" src="https://user-images.githubusercontent.com/3900482/66260563-6540e680-e7c0-11e9-9bc3-2a7a4b1fd1ff.png">
<img width="596" alt="Screenshot 2019-10-05 at 22 28 40" src="https://user-images.githubusercontent.com/3900482/66260564-6540e680-e7c0-11e9-9afa-94433f736df2.png">
<img width="578" alt="Screenshot 2019-10-05 at 22 33 09" src="https://user-images.githubusercontent.com/3900482/66260565-6540e680-e7c0-11e9-8f8d-f108f890b84a.png">
<img width="851" alt="Screenshot 2019-10-05 at 22 27 13" src="https://user-images.githubusercontent.com/3900482/66260580-94575800-e7c0-11e9-9455-a7f6b2620ced.png">
<img width="614" alt="Screenshot 2019-10-05 at 22 27 39" src="https://user-images.githubusercontent.com/3900482/66260588-b6e97100-e7c0-11e9-942e-67dd5e8cdead.png">

**Comment by GlenDC** [comment] 2019-10-07 08:54
Wallet CLI Commands now all support Custody Fees where required:

```
$ goldchainc wallet list unlocked | tail -n 30
ID: 0e8cea53abc7536752a2d8e0f51e13c4b077650670ddb2b82891dfac3754b1ed
Creation Value: 10 GFT
Current Age: 20h32m10s
Spendable Value: 9.999786084 GFT
Custody Fee To Be Paid: 0.000213916 GFT
Condition:
{"value":"10000000000","condition":{"type":1,"data":{"unlockhash":"015a080a9259b9d4aaa550e2156f49b1a79a64c7ea463d810d4493e8242e6791584fbdac553e6f"}}}

ID: 77690d138b78ca7d000d5dfa1c3313dd487b301579e09c64efb67036bcc032dd
Creation Value: 10 GFT
Current Age: 21h15m57s
Spendable Value: 9.999778483 GFT
Custody Fee To Be Paid: 0.000221517 GFT
Condition:
{"value":"10000000000","condition":{"type":1,"data":{"unlockhash":"015a080a9259b9d4aaa550e2156f49b1a79a64c7ea463d810d4493e8242e6791584fbdac553e6f"}}}

ID: 67ba41669274768e551ab36f2a3259fc2da8360b9725c5037dfaba73da5b6e57
Creation Value: 10 GFT
Current Age: 1h26m52s
Spendable Value: 9.999984919 GFT
Custody Fee To Be Paid: 0.000015081 GFT
Condition:
{"value":"10000000000","condition":{"type":1,"data":{"unlockhash":"015a080a9259b9d4aaa550e2156f49b1a79a64c7ea463d810d4493e8242e6791584fbdac553e6f"}}}

Unlocked unspent blockstake outputs:
ID: 96e1a83d6fcf994a6322f5698e63950e4e2b4eff57e0de7bcd2ffcd78603e813
Value: 3000 BS
Condition:
{"value":"3000","condition":{"type":1,"data":{"unlockhash":"015a080a9259b9d4aaa550e2156f49b1a79a64c7ea463d810d4493e8242e6791584fbdac553e6f"}}}
```

```
$ goldchainc wallet transactions
        1250   1d3f0c227ac1f2877550cc7f28ede9ba8701b2e3fdc7b5db832bd60423ff38ce          10.00 GFT             0 BS
        1250   547b7329fe76d1221304f5de14d14ba63453036eb65f40224deed916e70b967b           0.00 GFT             0 BS
        1251   2d86d3add644f03401d005974c048e4ec6c5c8db0ffa8e2d2dbd529cda463911          11.00 GFT             0 BS
        1251   f75187344017ba8b3df11cff95e74161c3b30a9413d059a76630025d83c8470b           0.00 GFT             0 BS
        1251   fc11f4371be4872d4d5695d7253aab3a6d3e463a40248986dc6518580a7d0ccc       -2232.05 GFT             0 BS
        1252   e62ea232589d6882a0f23938157cd796d6dad7b92f5cb0fa0ec1dd66a5f21c4e          10.00 GFT             0 BS
```

> We still only show one number, but it does include paid custody fees and incoming values are
> only showing spendable as well. For example at height `1251` I spent 42 GFT but I had to pay
> quite a lot of custody fees for the spent coin input.

```
$ goldchainc wallet
Wallet status:
Unencrypted, Unlocked
Confirmed Balance:   98540523.036908041 GFT
Locked Balance:      0 GFT
Custody Fees To Pay: 11.330523683 GFT
Unconfirmed Delta:   + 0 GFT
BlockStakes:         3000 BS
```

**Comment by GlenDC** [comment] 2019-10-09 06:58
Minting Extension is now also once again fully supported, with custody fee support for burn transaction functionality.

Example:

```
$ goldchainc wallet burn coins 42.321
69841a92f8c9ca81c9981dfdb10379ec4a2af586ed56372cabf7f6e47ae8d404
```

<img width="666" alt="Screenshot 2019-10-09 at 08 57 10" src="https://user-images.githubusercontent.com/3900482/66458372-e6270900-ea72-11e9-8502-bb037194ed87.png">

**Closed** 2019-10-09 15:42 UTC
Labels: type_feature

**Comment by GlenDC** [comment] 2019-10-11 10:17
Screenshots of desktop wallet:

<img width="882" alt="Screenshot 2019-10-10 at 23 01 22" src="https://user-images.githubusercontent.com/3900482/66644385-19a79600-ec21-11e9-8f25-189d44860e7f.png">
<img width="875" alt="Screenshot 2019-10-10 at 23 05 10" src="https://user-images.githubusercontent.com/3900482/66644386-19a79600-ec21-11e9-8937-759b45203dd6.png">
<img width="851" alt="Screenshot 2019-10-11 at 11 48 10" src="https://user-images.githubusercontent.com/3900482/66644387-19a79600-ec21-11e9-8d50-5372b109e8a8.png">
