### ISSUE TITLE
goldchain testnet bootstrap node down

### ISSUE THREAD

**Issue by LeeSmet** [nbh-digital/goldchain#37] opened 2019-07-29 07:27 UTC
bootstrap node 5 seems to have crashed around 11:25 AM yesterday, no clue as to why this happned. block creator running on it is obviously offline, slowing the network, and zerotier confirms the node hasn't been seen since that time

**Comment by GlenDC** [comment] 2019-07-29 07:30
No logs/output?

**Comment by LeeSmet** [comment] 2019-07-29 08:02
Node was unreachable, after manual reboot it is back operational

**Comment by GlenDC** [comment] 2019-07-29 08:05
How it could become unreachable? Is there an open rivine bug for this? is there something we can do about this or is it not related to rivine but instead caused by the network it is operational within?

**Comment by LeeSmet** [comment] 2019-07-29 09:00
Not rivine related. It seems that the node had a kernel panic or something similar, I had a previous issue with this kind of hardware where a CPU could lock after a while (presumably due to a bad power supply)

**Comment by LeeSmet** [comment] 2019-07-29 09:03
No logs found on the system, for now the system is back operations, if it happens again, we can look into further measures to identify the root cause

**Comment by GlenDC** [comment] 2019-07-29 09:10
Ok sounds good. Shall we close this issue than as wontfix or what do you propose?

**Comment by LeeSmet** [comment] 2019-07-29 09:18
Fine by me, will reopen this if the issue pops up again

**Comment by LeeSmet** [comment] 2019-07-31 14:26
Bootstrap 4 went down roughly 27 mins ago (around 4PM local time)

**Closed** 2019-08-02 16:47 UTC
Labels: type_bug
